name: "Main"
on:
  - push

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
      datetime: ${{ steps.get-datetime.outputs.datetime }}
    steps:
      - id: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT
      - id: get-datetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

  build:
    needs: [configure]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run linter
        run: pnpm lint
      - name: Run formatter
        run: pnpm format
      - name: Build
        run: pnpm build
